import { Injectable, CanActivate, ExecutionContext, UnauthorizedException } from '@nestjs/common';
import { FirebaseService } from '../firebase/firebase.service';

@Injectable()
export class JwtAuthGuard implements CanActivate {
  constructor(private firebaseService: FirebaseService) {}

  async canActivate(context: ExecutionContext): Promise<boolean> {
    const request = context.switchToHttp().getRequest();
    const authHeader = request.headers.authorization;

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      throw new UnauthorizedException('No authorization token provided');
    }

    const token = authHeader.split('Bearer ')[1];

    try {
      const decodedToken = await this.firebaseService.auth.verifyIdToken(token);
      
      // Map Firebase ID Token to the request.user object
      request.user = {
        userId: decodedToken.uid, // Preserved CUID
        email: decodedToken.email,
        role: decodedToken.role || 'USER', // Custom claim mapped during login/migration
        companyId: decodedToken.companyId || null, // Custom claim mapped during login/migration
      };

      return true;
    } catch (error) {
      // Fallback: If it's a Custom Token generated by our login, verify it with our service account private key!
      try {
        const jwt = await import('jsonwebtoken');
        const cert = this.firebaseService.serviceAccount.private_key;
        // The web app persists the backend-issued custom token as its session token.
        // Accept the signed token even after Firebase's default custom-token TTL so
        // existing sessions do not drop back to anonymous state on restart.
        const decodedCustom = jwt.verify(token, cert, {
          algorithms: ['RS256'],
          ignoreExpiration: true,
        }) as any;
        
        const userId = decodedCustom.uid || decodedCustom.sub;
        
        // Retrieve fresh user info from Firestore to populate roles and claims securely
        const userSnap = await this.firebaseService.db.collection('users').doc(userId).get();
        if (!userSnap.exists) {
          throw new UnauthorizedException('User not found');
        }
        const user = userSnap.data() as any;

        request.user = {
          userId,
          email: user.email,
          role: user.role || 'USER',
          companyId: user.companyId || null,
        };

        return true;
      } catch (err) {
        throw new UnauthorizedException('Invalid or expired authorization token');
      }
    }
  }
}
